name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Compress files
      run: |
        zip -r dist.zip dist

    - name: Copy ZIP file to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa dist.zip ubuntu@${{ secrets.EC2_HOST }}:/app
